git:
  submodules: false
sudo: required
services:
- docker
branches:
  except:
    - gh-pages
    - master
before_install:
- openssl aes-256-cbc -K $encrypted_986e194655d1_key -iv $encrypted_986e194655d1_iv
  -in secrets.tar.gz.enc -out secrets.tar.gz -d
- tar xvzf secrets.tar.gz
script:
- docker run -v $(pwd):/mnt --rm -t -e TRAVIS_TAG=${TRAVIS_TAG} fedora:latest /mnt/scripts/build
deploy:
  skip_cleanup: true
  provider: script
  script: docker run -v $(pwd):/mnt --rm -t -e TRAVIS_TAG=${TRAVIS_TAG} fedora:latest /mnt/scripts/deploy
  on:
    tags: true
